// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0

package database

import (
	"database/sql"
	"time"

	"github.com/google/uuid"
)

type Category struct {
	ID          uuid.UUID
	Name        string
	Description sql.NullString
}

type Product struct {
	ID         uuid.UUID
	Name       string
	Quantity   int32
	UserID     uuid.UUID
	CategoryID uuid.UUID
}

type User struct {
	ID        uuid.UUID
	CreatedAt time.Time
	UpdatedAt time.Time
	Username  string
	Password  string
	Name      string
	ApiKey    string
}
