// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0
// source: product.sql

package database

import (
	"context"
	"database/sql"
	"time"

	"github.com/google/uuid"
)

const createProduct = `-- name: CreateProduct :one
INSERT INTO product (id, created_at, updated_at, name, quantity, user_id, category_id) 
VALUES ($1, $2, $3, $4, $5,$6, $7)
RETURNING id, created_at, updated_at, name, quantity, user_id, category_id
`

type CreateProductParams struct {
	ID         uuid.UUID
	CreatedAt  time.Time
	UpdatedAt  time.Time
	Name       string
	Quantity   int32
	UserID     uuid.UUID
	CategoryID uuid.UUID
}

func (q *Queries) CreateProduct(ctx context.Context, arg CreateProductParams) (Product, error) {
	row := q.db.QueryRowContext(ctx, createProduct,
		arg.ID,
		arg.CreatedAt,
		arg.UpdatedAt,
		arg.Name,
		arg.Quantity,
		arg.UserID,
		arg.CategoryID,
	)
	var i Product
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Name,
		&i.Quantity,
		&i.UserID,
		&i.CategoryID,
	)
	return i, err
}

const getProduct = `-- name: GetProduct :many
SELECT product.id, created_at, updated_at, product.name, quantity, user_id, category_id, category.id, category.name, description FROM product
INNER JOIN category ON product.category_id = category.id
`

type GetProductRow struct {
	ID          uuid.UUID
	CreatedAt   time.Time
	UpdatedAt   time.Time
	Name        string
	Quantity    int32
	UserID      uuid.UUID
	CategoryID  uuid.UUID
	ID_2        uuid.UUID
	Name_2      string
	Description sql.NullString
}

func (q *Queries) GetProduct(ctx context.Context) ([]GetProductRow, error) {
	rows, err := q.db.QueryContext(ctx, getProduct)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetProductRow
	for rows.Next() {
		var i GetProductRow
		if err := rows.Scan(
			&i.ID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Name,
			&i.Quantity,
			&i.UserID,
			&i.CategoryID,
			&i.ID_2,
			&i.Name_2,
			&i.Description,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getProductByID = `-- name: GetProductByID :one
SELECT product.id, created_at, updated_at, product.name, quantity, user_id, category_id, category.id, category.name, description FROM product
INNER JOIN category ON product.category_id = category.id
WHERE product.id = $1
`

type GetProductByIDRow struct {
	ID          uuid.UUID
	CreatedAt   time.Time
	UpdatedAt   time.Time
	Name        string
	Quantity    int32
	UserID      uuid.UUID
	CategoryID  uuid.UUID
	ID_2        uuid.UUID
	Name_2      string
	Description sql.NullString
}

func (q *Queries) GetProductByID(ctx context.Context, id uuid.UUID) (GetProductByIDRow, error) {
	row := q.db.QueryRowContext(ctx, getProductByID, id)
	var i GetProductByIDRow
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Name,
		&i.Quantity,
		&i.UserID,
		&i.CategoryID,
		&i.ID_2,
		&i.Name_2,
		&i.Description,
	)
	return i, err
}

const updateProduct = `-- name: UpdateProduct :one
UPDATE product 
SET updated_at = NOW(), 
name = $1,
quantity = $2
WHERE id = $3
RETURNING id, created_at, updated_at, name, quantity, user_id, category_id
`

type UpdateProductParams struct {
	Name     string
	Quantity int32
	ID       uuid.UUID
}

func (q *Queries) UpdateProduct(ctx context.Context, arg UpdateProductParams) (Product, error) {
	row := q.db.QueryRowContext(ctx, updateProduct, arg.Name, arg.Quantity, arg.ID)
	var i Product
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Name,
		&i.Quantity,
		&i.UserID,
		&i.CategoryID,
	)
	return i, err
}
